# Generated by Django 6.0.3 on 2026-03-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_compra', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion_entrega', models.CharField(blank=True, max_length=200, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallesCompra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'tb_detalles_compra',
                'managed': False,
            },
        ),
    ]
