# Generated by Django 6.0.3 on 2026-03-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id_certificado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_certificado', models.CharField(max_length=100)),
                ('descripcion_cert', models.CharField(max_length=255)),
                ('fecha_expedicion', models.DateField()),
            ],
            options={
                'db_table': 'tb_certificados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_maquina', models.CharField(max_length=50)),
                ('documento_propiedad', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('registro_rnma', models.CharField(blank=True, db_column='registro_RNMA', max_length=200, null=True)),
                ('tarjeta_registro_maquinaria', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'tb_maquinas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'tb_servicios',
                'managed': False,
            },
        ),
    ]
