# Generated by Django 6.0.3 on 2026-03-18 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contrasena_usuario', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('rol', models.CharField(max_length=50)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administradore',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('privilegios_admin', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tb_administradores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipo_asesoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_asesores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('preferencias', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tb_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('tipo_cultivo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tb_productores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('zonas_entrega', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'tb_transportistas',
                'managed': False,
            },
        ),
    ]
