# Generated by Django 6.0.2 on 2026-03-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('privilegios_admin', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tb_administradores',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Administradore',
        ),
    ]
