# Generated by Django 6.0.3 on 2026-03-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_categorias_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id_finca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_finca', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_finca', models.CharField(blank=True, max_length=200, null=True)),
                ('certificado_bpa', models.CharField(blank=True, db_column='certificado_BPA', max_length=200, null=True)),
                ('certificado_mirfe', models.CharField(blank=True, db_column='certificado_MIRFE', max_length=200, null=True)),
                ('certificado_mipe', models.CharField(blank=True, db_column='certificado_MIPE', max_length=200, null=True)),
                ('registro_ica', models.CharField(blank=True, db_column='registro_ICA', max_length=200, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tb_fincas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesProducto',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('url_imagen', models.CharField(max_length=255)),
                ('es_principal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_imagenes_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'tb_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoFinca',
            fields=[
                ('id_producto_finca', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_produccion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_cosecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_productos_fincas',
                'managed': False,
            },
        ),
    ]
