# Generated by Django 6.0.2 on 2026-03-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calificacion',
            options={},
        ),
    ]
